### ISSUE TITLE
performance vs libvorbis

### ISSUE THREAD

**Issue by weepy** [mendsley/stbvorbis#1]
hey there,

Nice library - I'm trying to evaluate which library to use to decode some OGGs.

I read the page here http://nothings.org/stb_vorbis/  -- you mentioned you were maybe 2x slower than libvorbis . Is this still the case ? 

Thanks

Jonah

**Comment by mendsley** [comment]
This repository is a logical fork of https://github.com/nothings/stb - specifically the stb_vorbis.c file. It's not a proper fork because the official repository did not exist while this fork was under development.

As for your original question, it's likely this version of stb_vorbis is still 2x slower than the xiph.org reference library. Check the official repository for new performance data, though.
